spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    # hibernate:
    #   ddl-auto: create-drop

  main:
    banner-mode: "off"

security:
  oauth2:
    client:
      scope: password
      client-id: clientid
      client-secret: 123456
logging:
  pattern:
    console: |
      %d{dd-MM-yyyy HH:mm:ss} %highlight(%-5level) %logger.%M - %msg%n

## old
#server.port=9090
#spring.jpa.database=POSTGRESQL
#spring.datasource.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/spring1
#spring.datasource.username=willian
#spring.datasource.password=123456
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
